<a href="https://colab.research.google.com/github/profteachkids/CHE5136_Fall2021/blob/main/2DHeatConduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.io as pio
pio.templates.default='plotly_dark'
from scipy.optimize import newton_krylov

In [12]:


# parameters
nx, ny = 25, 25
hx, hy = 1./(nx-1), 1./(ny-1)

P_left, P_right = 0, 0
P_top, P_bottom = 1, 0

def residual(P):
    d2x = np.zeros_like(P)
    d2y = np.zeros_like(P)

    d2x[1:-1] = (P[2:]   - 2*P[1:-1] + P[:-2]) / hx/hx
    d2x[0]    = (P[1]    - 2*P[0]    + P_left)/hx/hx
    d2x[-1]   = (P_right - 2*P[-1]   + P[-2])/hx/hx

    d2y[:,1:-1] = (P[:,2:] - 2*P[:,1:-1] + P[:,:-2])/hy/hy
    d2y[:,0]    = (P[:,1]  - 2*P[:,0]    + P_bottom)/hy/hy
    d2y[:,-1]   = (P_top   - 2*P[:,-1]   + P[:,-2])/hy/hy

    return d2x + d2y

# solve
guess = np.zeros((nx, ny))
sol = newton_krylov(residual, guess, method='lgmres', verbose=0)

In [5]:
x, y = np.mgrid[0:1:(nx*1j), 0:1:(ny*1j)]

In [17]:
sol.shape

(25, 25)

In [24]:
fig = make_subplots()
for i in np.arange(nx):
     fig.add_trace(go.Scatter3d(x=x[i,:], y=y[i,:], z=sol[i,:], mode='lines', line_color='gray'))

for j in np.arange(ny):
     fig.add_trace(go.Scatter3d(x=x[:,j], y=y[:,j], z=sol[:,j], mode='lines', line_color='gray'))

fig.update_layout(width=800, height=800, scene=dict(xaxis_title='x', yaxis_title='y', zaxis_title='T'),
                  showlegend=False)

In [ ]:
ShGrid

array([[  3.15966765,   3.68627893,   4.2128902 ,   4.73950148,
          5.26611275,   5.79272403,   6.31933531,   6.84594658,
          7.37255786,   7.89916913,   8.42578041,   8.95239168,
          9.47900296,  10.00561423,  10.53222551,  11.05883678,
         11.58544806,  12.11205934,  12.63867061,  13.16528189],
       [  5.30986596,   6.19484362,   7.07982128,   7.96479894,
          8.8497766 ,   9.73475426,  10.61973192,  11.50470958,
         12.38968724,  13.2746649 ,  14.15964256,  15.04462022,
         15.92959788,  16.81457554,  17.6995532 ,  18.58453085,
         19.46950851,  20.35448617,  21.23946383,  22.12444149],
       [  7.29035914,   8.505419  ,   9.72047886,  10.93553871,
         12.15059857,  13.36565843,  14.58071828,  15.79577814,
         17.010838  ,  18.22589786,  19.44095771,  20.65601757,
         21.87107743,  23.08613728,  24.30119714,  25.516257  ,
         26.73131685,  27.94637671,  29.16143657,  30.37649643],
       [  9.16518835,  10.69271974,  

In [ ]:
ReGrid

In [ ]:
x=np.linspace(0,3,4)
y=np.linspace(5,8, 4)

In [ ]:
for i,j in zip(x,y):
    print(i,j)

0.0 5.0
1.0 6.0
2.0 7.0
3.0 8.0


In [ ]:
xx,yy = np.meshgrid(x,y)

In [ ]:
for ix, iy in zip(xx,yy):
    print(ix,iy)

[0. 1. 2. 3.] [5. 5. 5. 5.]
[0. 1. 2. 3.] [6. 6. 6. 6.]
[0. 1. 2. 3.] [7. 7. 7. 7.]
[0. 1. 2. 3.] [8. 8. 8. 8.]


In [ ]:
xx

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [ ]:
yy

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.],
       [8., 8., 8., 8.]])

In [ ]:
xx

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.]])

In [ ]:
yy

array([[5., 6., 7., 8., 9.],
       [5., 6., 7., 8., 9.],
       [5., 6., 7., 8., 9.],
       [5., 6., 7., 8., 9.]])

In [ ]:
x=np.lin