<a href="https://colab.research.google.com/github/profteachkids/CHE5136_Fall2021/blob/main/IntermediateEqualAreaHistogram.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from plotly.subplots import make_subplots
import plotly.io as pio
pio.templates.default='plotly_dark'

In [101]:
N = int(100)
Nbins = 10

In [102]:
data = np.arange(0,100,1)
data = np.sort(data)

In [113]:
if (N % Nbins) == 0:
    NPerBin= N // Nbins
    NLastBin = N
    BinArea=NPerBin * 1/N
    LastBinArea = 0
    edges = data[::NPerBin]
    edges = np.append(edges, data[-1])

In [114]:
edges

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 99])

In [111]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [107]:
np.append(edges,data[-1])

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 99])

In [46]:
height = 1/Nbins/(edges[1:]-edges[:-1])

In [58]:
edges

array([-2.51816891, -1.46420736, -0.64100271, -0.36847454, -0.1172351 ,
        0.19183618,  0.35149277,  0.62310245,  1.17167985,  2.21412799])